copy %1 "../../Idle of the Ages/Assets/StreamingAssets/Mods/IdleOfTheAgesGame/"
copy %2 "../../Idle of the Ages/Assets/StreamingAssets/Mods/IdleOfTheAgesGame/"
copy %3 "../../Idle of the Ages/Assets/StreamingAssets/Mods/IdleOfTheAgesGame/"
copy %4 "../../Idle of the Ages/Assets/StreamingAssets/Mods/IdleOfTheAgesGame/"
xcopy /Y /E /I %5 "../../Idle of the Ages/Assets/StreamingAssets/Mods/IdleOfTheAgesGame/Assets"